services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_USER=${POSTGRESDB_USER}
    ports:
      - '${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}'
    networks:
      - kaya-network

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}'
      - 'PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}'
    ports:
      - '${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}'
    networks:
      - kaya-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
    networks:
      - kaya-network

networks:
  kaya-network:
    driver: bridge